Repository oclif/plugin-update, pull requests merged in 2024-05, with the labels that each got.

#807 fix: new "dont check npm" option
  src/update.ts
Labels: cla:signed, enhancement

#812 fix: dont check npm option - #797 (#807)
  package.json
  src/update.ts
  yarn.lock
Labels: cla:signed

#820 fix: no error when using --force
  package.json
  src/tar.ts
  src/update.ts
  test/update.test.ts
  yarn.lock
Labels: enhancement
